version: '2.1'
services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - DL_APP_KEY=${DL_APP_KEY}
      - DL_SESSION_ID=${DL_SESSION_ID}
    entrypoint: ['/bin/bash', 'entrypoint.sh']
    depends_on:
      - postgres
    
volumes:
  database-data: